service: crm-app
provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: false
      - http:
          path: /{proxy+}
          method: ANY
          cors: false
