AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: An AWS Serverless Specification template describing your function.
Resources:
  crmappproductionapp:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: lambda.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: ""
      MemorySize: 128
      Timeout: 6
      Role: "arn:aws:iam::286506837327:role/crm-app-production-us-east-1-lambdaRole"
      Events:
        Api1:
          Type: Api
          Properties:
            Path: "/{proxy+}"
            Method: ANY
      Environment:
        Variables:
          CRM_DB: >-
            mongodb+srv://crmAdmin:<password_here>@cluster0.m8s54.mongodb.net/<dbname>?retryWrites=true&w=majority
          NODE_ENV: production
      Tags:
        STAGE: production
